[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-ngrok>=0.0.25",
    "flask>=3.1.0",
    "requests>=2.32.3",
]
